version: "3.6"

services:
  db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:
